version: '3.8'
services:
  frontend:
    build:
      context: ./Frontend/CarManagementSystem
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    networks:
      - car-rental-network
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
    networks:
      - car-rental-network
    env_file:
      - ./Backend/.env 
    environment:
      MONGODB_URI: mongodb://mongo_db_container:27017/carRentalSystem
      PORT: 3001 
    depends_on:
      - mongo_db_container
    restart: unless-stopped
  mongo_db_container:
    image: mongo:latest 
    ports:
      - "27017:27017" 
    networks:
      - car-rental-network
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped
networks:
  car-rental-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local 