apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: scd-project
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb 
  type: ClusterIP
 