name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker to use Minikube's environment
      run: minikube docker-env | Invoke-Expression
      shell: powershell

    - name: Build Backend Docker image
      run: |
        cd Backend
        docker build -t tahaawan2/car-rental-backend:latest .
     

    - name: Build Frontend Docker image
      run: |
        cd Frontend/CarManagementSystem
        docker build -t tahaawan2/car-rental-frontend:latest .
      shell: powershell

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Backend Docker image
      run: docker push tahaawan2/car-rental-backend:latest
     

    - name: Push Frontend Docker image
      run: docker push tahaawan2/car-rental-frontend:latest
      

    - name: Deploy MongoDB to Minikube
      run: |
        kubectl apply -f mongodb-deployment.yaml
        kubectl apply -f mongodb-service.yaml

    - name: Deploy Backend to Minikube
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl rollout restart deployment backend-deployment
        kubectl apply -f backend-service.yaml


    - name: Deploy Frontend to Minikube
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl rollout restart deployment frontend-deployment
        kubectl apply -f frontend-service.yaml 

        